{% set name = "pytest-helpers-namespace" %}
{% set version = "2021.12.29" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-helpers-namespace-{{ version }}.tar.gz
  sha256: 792038247e0021beb966a7ea6e3a70ff5fcfba77eb72c6ec8fd6287af871c35b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pytest >=2.9.1
    - python >={{ python_min }}

test:
  imports:
    - pytest_helpers_namespace
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/saltstack/pytest-helpers-namespace
  summary: PyTest Helpers Namespace
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
